name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v2
       with:
         fetch-depth: 2
       
     - name: Dump GitHub context
       run: |
          echo  ${{secrets.TEST_SECRET}} > test.txt
          cat  test.txt > test2.txt
          cat test2.txt
  
