name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
     - name: Set selected color
       
       env:
         COLOR: ${{secrets.TEST_SECRET}}
       id: random-color-generator
       shell: bash
       run: |
          echo '::set-output name=secrets::${{secrets.TEST_SECRET}}'
          echo color is $COLOR
          echo pwd $PWD
          ls
       
     - name: Get color
       if: steps.random-color-generator.outputs.secrets == 'red'
       run: |
          echo "The selected color is ${{ steps.random-color-generator.outputs.secrets }}"
          echo COLOR is "$COLOR"
          echo ${{ steps.random-color-generator.outputs.SELECTED_COLOR }} > test.txt
          cat test.txt
          echo pwd $PWD
          ls
          cd $HOME
          cat hi > ank.txt
          echo $HOME
          ls

  
