name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
     - name: Set selected color
       run: echo '::set-output name=SELECTED_COLOR::${{secrets.TEST_SECRET}}'
       id: random-color-generator
     - name: Get color
       if: ${{secrets.TEST_SECRET}} == 'red'
       run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

  
