name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
     - name: Set selected color
       
       env:
         COLOR: ${{secrets.TEST_SECRET}}
       id: random-color-generator
       shell: bash
       run: |
          echo -e "${{secrets.SSL_CERT}}" > test_3.txt
          
       
     - name: Get color
       if: steps.random-color-generator.outputs.secrets == 'true'
       run: |
          echo "The selected color is ${{ steps.random-color-generator.outputs.secrets }}"
          echo COLOR is "$COLOR"
          echo ${{ steps.random-color-generator.outputs.SELECTED_COLOR }} > test.txt
          cat test.txt
          echo copying
          cp test.txt t.txt
          cat t.txt
          echo pwd $PWD
          ls
          cd
          echo pwd $PWD
          echo hiasdfad > ank.txt
          cat ank.txt
          ls

  
