name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
     - name: Set selected color
       run: echo '::set-output name=secrets::${{secrets.TEST_SECRET}}'
       id: random-color-generator
     - name: Get color
       if: steps.random-color-generator.outputs.secrets == 'red'
       run: |
          echo "The selected color is ${{ steps.random-color-generator.outputs.secrets }}",
          echo ${{ steps.random-color-generator.outputs.SELECTED_COLOR }} > test.txt
          cat test.txt

  
