name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v2
       
     - name: Dump GitHub context
       run: git diff --name-only HEAD~1 HEAD
  
