name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
     - name: Dump GitHub context
       run: |
          echo "========== list modified files ============"
          git diff --name-only HEAD^ HEAD
  
