name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy-test:
    if: ${{contains(github.event.head_commit.modified,'test')}}
    runs-on: ubuntu-latest
    steps:
     - name: Dump GitHub context
       run: echo "${{github}}"
  
